<a href="https://colab.research.google.com/github/Asadullahkhankaimkhani/Tensorflow2.0_Certification/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we're going to cover some of the most fundamental concepts of tensors using tensorflow

More specifically , we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function(a way to speed up your regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Excerise to try for yourself


## Introducation to Tensors

In [3]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
#create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check dimension of our vector
vector.ndim

1

In [ ]:
#create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [20,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [20, 11]], dtype=int32)>

In [ ]:
#check dimension of matrix 
matrix.ndim

2

In [ ]:
#create another matrix 
another_matrix = tf.constant([[10,5],
                              [2.,2.],
                              [8.,9.]],dtype=tf.float16) #specify the data type with 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 2.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#let create a tensor 
tensor = tf.constant([[[1,2,3],
                     [4,5,6]],
                      [[7,8,9],
                     [10,11,12],],
                     [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### what we've created so far
 * Scalar : a single number
 * Vector : a number with direction (e.g wind speed and direction)
 * Matrix : a 2-dimensional array of number
 * Tensor : an n-dimensional array of number (when n can be any number)

#Create Tf.varaiable

In [6]:
# create same tensor with tf.varaiable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

unchangeable_tensor,changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
#change try change one of the elements in our changeable tensor
changeable_tensor[0].assign( 7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>