<a href="https://colab.research.google.com/github/Asadullahkhankaimkhani/Tensorflow2.0_Certification/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we're going to cover some of the most fundamental concepts of tensors using tensorflow

More specifically , we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function(a way to speed up your regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Excerise to try for yourself


## Introducation to Tensors

In [3]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
#create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check dimension of our vector
vector.ndim

1

In [ ]:
#create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [20,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [20, 11]], dtype=int32)>

In [ ]:
#check dimension of matrix 
matrix.ndim

2

In [ ]:
#create another matrix 
another_matrix = tf.constant([[10,5],
                              [2.,2.],
                              [8.,9.]],dtype=tf.float16) #specify the data type with 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 2.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#let create a tensor 
tensor = tf.constant([[[1,2,3],
                     [4,5,6]],
                      [[7,8,9],
                     [10,11,12],],
                     [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### what we've created so far
 * Scalar : a single number
 * Vector : a number with direction (e.g wind speed and direction)
 * Matrix : a 2-dimensional array of number
 * Tensor : an n-dimensional array of number (when n can be any number)

#Create Tf.varaiable

In [6]:
# create same tensor with tf.varaiable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

unchangeable_tensor,changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [10]:
#change try change one of the elements in our changeable tensor
changeable_tensor[0].assign( 7)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

###Create Random Tensor

In [13]:
##random tensors are of some abitrary size conatain random numbers

In [20]:
#create two random (but the same ) tensor
random_1 = tf.random.Generator.from_seed(42) # set of seed for reproducibility
random_1 = random_1.normal(shape=(3,2,3))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2,3))

random_1,random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ]],
 
        [[ 0.09988727, -0.50998646, -0.7535805 ],
         [-0.57166284,  0.1480774 , -0.23362993]],
 
        [[-0.3522796 ,  0.40621263, -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ]],
 
        [[ 0.09988727, -0.50998646, -0.7535805 ],
         [-0.57166284,  0.1480774 , -0.23362993]],
 
        [[-0.3522796 ,  0.40621263, -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 ]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=bool, numpy=
 array([[[ True,  True,  True],
         [ True,  True,  True]],
 
        [[ True,  True,  True],
         [ True,  True,  True]],
 
        [[ True,  True,  True],
         [ True,  True,  True]]

##Shuffle the order of elemets in a tensor

In [27]:
## Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesnt effect learning  )
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [12,133]])
## shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 12, 133],
       [ 10,   7],
       [  3,   4]], dtype=int32)>

In [36]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 10,   7],
       [  3,   4],
       [ 12, 133]], dtype=int32)>

##Others ways to make tensors

In [42]:
## create a tensor of all ones 
tf.ones([2,3],tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [48]:
#create a tensor of all zeros
tf.zeros([3,11],tf.int32)

<tf.Tensor: shape=(3, 11), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [50]:
#the main differnce between Numpy arrays and tensorflow tenors is that
# tensors can be run on a GPU (much faster for numerical computing)
import numpy as np
numpy_A =  np.arange(1,25, dtype=np.int32)
numpy_A

# you can also turn Numpy arrays into tensors 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [61]:
A = tf.constant(numpy_A, shape=(2,3,4,))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensor

*   Shape
*   Rank
*   Axis or dimension
*   Size



In [90]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor,rank_4_tensor.ndim ,rank_4_tensor.shape

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>,
 4,
 TensorShape([2, 3, 4, 5]))

In [91]:
#Get various attributes of our tensor 

print('Datatype of every element:',rank_4_tensor.dtype)
print('Number of Dimension:',rank_4_tensor.ndim)
print('Shape of tensor:',rank_4_tensor.shape)
print('Elements along the 0 axis:',rank_4_tensor.shape[0])
print('Elements along the last axis',rank_4_tensor.shape[-1])
print('Total number of element in out tensor',tf.size(rank_4_tensor))
print('Total number of element in out tensor',tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of Dimension: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis 5
Total number of element in out tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of element in out tensor 120


#Indexing tensors

###tensors can be indexed just like python lists

In [92]:
## Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [101]:
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [106]:
## Create a rank 2 tensor(2 dimension)
rank_2_tensor = tf.constant([[2,3],
                             [4,5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [127]:
## Get the last item of each of of our rank 2 tensor
rank_2_tensor[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [130]:
# Add in extra dimension to our rank 2 tensor 
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [132]:
## Alternante to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>